# Generated by Django 4.2.11 on 2024-04-17 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='dateReservation',
            new_name='date_reservation',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='dateRetour',
            new_name='date_retour',
        ),
    ]
